### ISSUE TITLE
How to have a production with multiple parameterised inputs

### ISSUE THREAD

**Issue by TMiguelT** [nylki/lindenmayer#12]
I want to create a production `+F => S` where both `+` and `F` are parameterised, so they are actually `{symbol: '+', value: 90}` and `{symbol: 'F', value: 1}`. Or, in classical notation, `+(a)F(b) => S(c)`. How do I make a production whose input is two parameterised symbols?

I expected this to work, but the production was never used, even though I know I had the sequence `+F` in my inputs.
```JavaScript
    productions: {
        '+F': ({part}) => {
            return [{
                symbol: 'C', value: part.value
            }]
        }
    }
```

**Comment by nylki** [comment]
Reducing the symbol count would be practical indeed but Its a formal restriction. As far as I am aware of, there is no example where more than one symbol is used as a production initiator in ABOP. This could get a bit messy if it was allowed (consider the axiom:`FF++` with multiple productions:  , `FF+ -> B`, `F -> A`, `FF++ -> C`, where multiple productions can apply at one place; which one would be applied  for lets say the first symbol? Also an issue is how to deal with branches via `[` and `]`.
I mean this could be implemented in one way or another but would introduce some serious issues like the above and wouldnt comply with the formal definition of an L-System.

What is usually done to achieve something you want to do, is to use the context-sensitive syntax (see page 30 in ABOP) and to cancel out unwanted symbols by different symbols .

First of all, a context sensitive production looks like:
```.js
  // apply production to every F that is preceded by a +
  productions: {
        '+<F': { symbol: 'C', value: part.value}
    }
```

In the above, lets say you have the word `FF+FF`, the above would return `FF+CF`. But I suppose you would like to have `FFCF`. In your case what could work: 

```.js
  productions: {
        '+<F': { symbol: '-C', value: part.value}
    }
  // would return FF+-CF
  // Which would cancel out the `+` with the `-`.
```

**Comment by nylki** [comment]
Was just testing my recommended alternative. Found a big in the lib that way. Because + and - where ignored when doing context sensitive comparison. Gonna fix it.

**Comment by TMiguelT** [comment]
Thanks! That's an interesting suggestion.

I'll try it out, although another way is possibly to get my turtle to just interpret a triplet of F+F differently (I want it to make a bezier curve instead of a sharp corner.
