### ISSUE TITLE
transformClassicCSProduction being passed two arguments but only accepting one

### ISSUE THREAD

**Issue by smlkhs** [nylki/lindenmayer#19]
On line 52 of lindenmayer.js we see the following: 

```javascript
if(this.allowClassicSyntax === true) {
        newProduction = transformClassicCSProduction(newProduction, this.ignoredSymbols);
}
```

Yet the function `transformClassicCSProduction` seems to take only one argument in transformersClassicSyntax.js.

```javascript
export function transformClassicCSProduction (p) {

  // before continuing, check if classic syntax actually there
  // example: p = ['A<B>C', 'Z']

  // left should be ['A', 'B']
  let left = p[0].match(/(.+)<(.)/);

  // right should be ['B', 'C']
  let right = p[0].match(/(.)>(.+)/);

  // Not a CS-Production (no '<' or '>'),
  //return original production.
  if(left === null && right === null) {
    return p;
  }
```
Is this intentional? I'm trying to model Tree B on page 43 of [this book](http://algorithmicbotany.org/papers/lsfp.pdf) by Przemyslaw Prusinkiewicz and James Hanan with  the respective L-system on the previous page (pg. 42) using your library but I believe there's a problem with how ignored symbols are passed.

**Comment by nylki** [comment]
Hi @smlkhs,
Good spot! It is a superflous remnant. In fact `transformClassicCSProduction` does not require the ignored symbols to transform a classic CS syntax to the internal syntax of context sensitive productions.

However, in the README, I state that the default value for ignored symbols is: `+-&^/|\\`, which is in fact false. I imagine that could have been a cause of incorrect results in your case if you did not specifiy them manually?

**Comment by nylki** [comment]
@smlkhs Let me know how it goes and if any other issues arise!

**Comment by smlkhs** [comment]
@nylki Great. I'll let you know if any other issues arise.
